### ISSUE TITLE
Samsung SSD 990 PRO shows error

### ISSUE THREAD

**Issue by garbast** [smartmontools/smartmontools#267] opened 2024-06-02 15:12 UTC
With version 7.4 i get an error:

`Read Self-test Log failed: Invalid Field in Command (0x002)`

Beside that, the 990 PRO is not listed in drivedb.h

**Comment by chrfranke** [comment] 2024-06-02 17:55
> With version 7.4 i get an error:
> 
> `Read Self-test Log failed: Invalid Field in Command (0x002)`
> 

This is likely the issue described in ticket [#1741](https://www.smartmontools.org/ticket/1741)

> Beside that, the 990 PRO is not listed in drivedb.h

Please see the [FAQ](https://www.smartmontools.org/wiki/FAQ#MyNVMedriveisnotinthesmartctlsmartddatabase).

**Comment by garbast** [comment] 2024-06-03 05:30
Thanks for your fast reply.

Trying out what was mentioned in the linked issue is working now:

`smartctl --all /dev/nvme0`

worked as described by Mark.

After reading the FAQ it was surprising to me to finde this block in the drivedb.h https://github.com/smartmontools/smartmontools/blob/65707ca59285a4b2350fb5b30293398f17e868bd/smartmontools/drivedb.h#L1959

**Comment by chrfranke** [comment] 2024-06-03 12:16
Closing as a duplicate of ticket [#1741](https://www.smartmontools.org/ticket/1741).

> After reading the FAQ it was surprising to me to finde this block in the drivedb.h ... `"Samsung based SSDs"`

This is unrelated to NVMe. Please create a new issue if there is any problem with this entry.

**Closed by chrfranke** 2024-06-03 12:16 UTC
Labels: duplicate

**Comment by chrfranke** [comment] 2024-10-23 16:34
Please see updated info in [recent comment of ticket #1741](https://www.smartmontools.org/ticket/1741#comment:13).
