### ISSUE TITLE
Help please: Read NVMe Identify Controller failed: IOCTL_STORAGE_QUERY_PROPERTY(NVMe) failed, Error=1

### ISSUE THREAD

**Issue by maainux** [smartmontools/smartmontools#164] opened 2022-12-30 19:20 UTC
Hi ,
I have 2 nvme drives, one samsung another adata xpg on a windws 11 laptop.I do not get SMART information anywhere. When I try smarttools, I get the below error.
`Read NVMe Identify Controller failed: IOCTL_STORAGE_QUERY_PROPERTY(NVMe) failed, Error=1`

Pleae help.

**Comment by maainux** [comment] 2022-12-30 19:22
The smartctl scan command yields the below output
`smartctl -d nvme --scan`
```
/dev/sda -d nvme # /dev/sda, NVMe device
/dev/sdb -d nvme # /dev/sdb, NVMe device
```

**Comment by chrfranke** [comment] 2022-12-30 20:27
Please always provide a full `smartctl` output because its first line contains important version information.

`Error 1` is `ERROR_INVALID_FUNCTION` which means that the NVMe driver does not support the required NVMe pass-through functionality. The generic driver `stornvme.sys` should support this functionality but unfortunately the Intel RST driver requires a vendor specific I/O-control, see [wiki page about NVMe support](https://www.smartmontools.org/wiki/NVMe_Support).

If the Intel RST driver is used on your system, see [ticket 1223](https://www.smartmontools.org/ticket/1223).

**Comment by chrfranke** [comment] 2023-01-26 17:49
Do you have any info about the driver used here?

**Comment by chrfranke** [comment] 2023-06-20 15:44
No feedback from reporter. If an Intel RST driver is used, this is a duplicate of [ticket 1223](https://www.smartmontools.org/ticket/1223).

**Closed by chrfranke** 2023-06-20 15:44 UTC
Labels: invalid
