### ISSUE TITLE
Broadcom/LSI RAID support for Windows (Server 2019)

### ISSUE THREAD

**Issue by domu83** [smartmontools/smartmontools#54] opened 2020-05-15 05:08 UTC
can you please add support for Windows for Broadcom / LSI RAID controllers?

Please PN me as I can support from the Broadcom site

**Comment by chrfranke** [comment] 2020-05-15 12:05
Duplicate of [ticket 1334](https://www.smartmontools.org/ticket/1334).

**Closed by chrfranke** 2020-05-15 12:05 UTC
