### ISSUE TITLE
Any plans to make new release?

### ISSUE THREAD

**Issue by kloczek** [smartmontools/smartmontools#36] opened 2019-05-27 14:06 UTC
I think that it would be good to make new release with updated code base :)

**Comment by chrfranke** [comment] 2019-06-07 13:04
Besides the regression fix (https://www.smartmontools.org/ticket/1154) there are no major changes since smartmontools 7.0. Most other changes are drivedb additions which could be updated separately, see:
https://www.smartmontools.org/query?status=closed&milestone=Release+7.1

Note that we provide automatic builds at https://builds.smartmontools.org/

Which specific changes for which platform do you need?

**Comment by kloczek** [comment] 2019-09-17 06:42
In this case more important is number of changes (not importance of them).
Really .. please make a bit more often minor releases.

**Comment by chrfranke** [comment] 2019-09-25 10:46
Due to small team size and limited open source spare time, there will be only ~one release per year, sorry.

**Comment by samm-git** [comment] 2019-10-16 12:40
@kloczek best approach to make releases more frequently is to join devteam and implement new features, we have a lot of them in our todo list: https://www.smartmontools.org/query?status=accepted&status=assigned&status=new&status=reopened&keywords=~&type=enhancement&col=id&col=summary&col=type&col=status&col=priority&col=milestone&col=component&order=priority

Closing for now as there is nothing to be done here

**Closed by samm-git** 2019-10-16 12:40 UTC

**Comment by kloczek** [comment] 2019-10-16 17:22
Issue is that last version of the smarmontools has been released almost year ago.
Since then in the repository already have been "4645 commits to master since this release".

**Comment by samm-git** [comment] 2019-10-16 17:56
@kloczek where 99% of this commits are `drivedb.h`related.

**Comment by kloczek** [comment] 2019-10-16 19:22
1% of 4.6k commits it is still ~50.
Other thing is that any driverdb.h updates cannot be applied in isolated installations withoutt access  network. With such rate of commits it would be good to have at least one minor release per month.

**Comment by samm-git** [comment] 2019-10-16 19:26
@kloczek please, stop spam. I reviewed changelog and i see 0 value in a release-to-make-release. For the isolated installation probably drivedb is a last thing needs to be updated. Anyway, i think it is very clear - if you want releases to be more frequent - contribute to the code. There are a lot of tasks to do and a lot of pieces needs some care.

**Comment by kloczek** [comment] 2019-10-16 19:29
Please do not tell me to read and review 4.6k git coommits.
Again seems you completly do not understand that there are many systems without access to public network which are updated only using distributoion updates.

**Comment by samm-git** [comment] 2019-10-16 19:32
Sorry, it became annoying. there is a https://builds.smartmontools.org/ server which hosts every build on a change with updated drive db. If you want to make something useful for the project - start coding and stop suggesting to developers what to do. Thank you.
