### ISSUE TITLE
`$SMARTD_DEVICETYPE` incorrectly set

### ISSUE THREAD

**Issue by pacien** [smartmontools/smartmontools#52] opened 2020-03-18 00:18 UTC
https://www.smartmontools.org/ticket/113 is happening again: the value of `$SMARTD_DEVICETYPE` is sometimes incorrect when using device auto-detection.

The log indicates that my device's type changed from "scsi" to "sat", but `$SMARTD_DEVICETYPE` is set to "scsi" when calling my notification script, breaking calls to smartctl.

```log
Mar 18 00:44:50 hp2 smartd[10516]: Device: /dev/sdd, type changed from 'scsi' to 'sat'
Mar 18 00:44:50 hp2 smartd[10516]: Device: /dev/sdd [SAT], opened
Mar 18 00:44:50 hp2 smartd[10516]: Device: /dev/sdd [SAT], […]
Mar 18 00:44:50 hp2 smartd[10516]: Device: /dev/sdd [SAT], is SMART capable. Adding to "monitor" list.
Mar 18 00:44:50 hp2 smartd[10516]: Monitoring 4 ATA/SATA, 0 SCSI/SAS and 0 NVMe devices
Mar 18 00:44:50 hp2 smartd[10516]: Executing test of /nix/store/7haj5vrsb5qk9pqa11yyz9d57q5n4pgi-smartd-notify.sh to <nomailer> ...
```

Version info: smartmontools 7.1 with driverdb 5033

**Comment by chrfranke** [comment] 2020-03-20 18:15
Please provide `smartd.conf` line for this device. Behavior of `DEVICESCAN` and `/dev/sdX` lines might differ.

**Comment by pacien** [comment] 2020-03-20 18:24
smartd.conf:
```
DEVICESCAN -m <nomailer> -M exec /nix/store/7haj5vrsb5qk9pqa11yyz9d57q5n4pgi-smartd-notify.sh -M test -a
```

**Comment by chrfranke** [comment] 2020-03-25 13:17
Please try this `smartd.conf` to check whether the problem is `DEVICESCAN` specific:
```
DEFAULT -m <nomailer> -M exec /nix/store/7haj5vrsb5qk9pqa11yyz9d57q5n4pgi-smartd-notify.sh -M test -a
/dev/sdd
```

PS: OT: The `DEFAULT` line in your `smartd.conf` does not make much sense as it results in a `DEVICESCAN` line with all directives specified twice. Either remove the `DEFAULT` line or remove all directives from the `DEVICESCAN` line.

**Comment by pacien** [comment] 2020-03-25 13:50
* With `DEVICESCAN`:  `$SMARTD_DEVICETYPE` is set to `scsi`
* With `/dev/sdd`: `$SMARTD_DEVICETYPE` is set to `auto`

This does appear to be specific to `DEVICESCAN`.

**Comment by chrfranke** [comment] 2020-03-25 17:55
Should be fixed in [r5039](https://www.smartmontools.org/changeset/5039) (216f749). Please test if possible.

See https://builds.smartmontools.org/ for source tarball and various binaries.

**Closed by chrfranke** 2020-03-25 17:55 UTC
Labels: bug

**Comment by pacien** [comment] 2020-03-25 19:16
I confirm that the patch solves the issue. Thanks!
